POST http://localhost:5000/item_emissions HTTP/1.1
Content-Type: application/json

{
    "item_name": "rice",
    "price": 2
}

####
POST http://localhost:5000/user/ HTTP/1.1
Content-Type: application/json

{
    "email": "maasd23@gmail.com",
    "username": "mehahahdasd",
    "password": "1283asndw"
}

####
POST http://localhost:5000/user_emission/ HTTP/1.1
Content-Type: application/json

{
    "user_id": "usr-K78oQQEe3zpswfTf5vA3vo0",
    "items":[
        {
            "item_name": "rice",
            "price_gbp": 1.5
        }
    ]
}